### ISSUE TITLE
Could I know if the figure below is not plotted completed?

### ISSUE THREAD

**Issue by liamxg** [TaishiNakase/MVSE#2]
Dear @TaishiNakase,

Could I know if the figure below is not plotted completed?

<img width="1071" alt="image" src="https://github.com/user-attachments/assets/7d4307fd-4a17-47ac-bdd7-07a9170fb712">

Best,
Liam

**Comment by TaishiNakase** [comment]
Dear Liam, 

Indeed, the figure is not plotted completely. You can change the scale of the y-axis with **scale_y_continuous**. 

-Taishi

**Comment by liamxg** [comment]
Dear @TaishiNakase ,

Thanks.

Liam
