### ISSUE TITLE
if I want to find the climate data for China, where should I get?

### ISSUE THREAD

**Issue by liamxg** [TaishiNakase/MVSE#3]
Dear @TaishiNakase,

if I want to find the climate data for China, where should I get?

Thanks.

Best,
Liam

**Comment by TaishiNakase** [comment]
Dear Liam, 

The climate data (relative humidity and temperature) can be obtained from Copernicus (https://cds.climate.copernicus.eu/cdsapp#!/dataset/ecv-for-climate-change). They do not provide climate data by administrative region (e.g. China), but you can crop to your desired area using relevant shape files (for example, see https://gadm.org). 

- Taishi
